name: "Windows"

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: clone-repository
        uses: actions/checkout@v3
      - name: build
        run: rustup install 1.70.0 && cargo +1.70.0 build --release
      - name: upload-dist
        if: true
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: target/release/wdb_transfer.exe
          retention-days: 1